spring:
  profiles:
    active: dev

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 3030
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    basedir: ./tmp